spring:
    config:
        import: file:local/.env[.properties]
    thymeleaf:
        check-template: false
    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL}
        password: ${EMAIL_PASS}
        sendTo: ${EMAIL_SEND_TO}
        protocol: smtps
        auth: true
        ssl-enable: true
        smtp-debug: true
    application:
        name: users-backend
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: ${front-url}/${realmsPath}/protocol/openid-connect/certs
    liquibase:
        change-log: migrations/v.1.0/db.changelog-v.1.0.yml
        url: jdbc:postgresql://localhost:5440/users-db
        user: users
        password: users-password
        enabled: false
    r2dbc:
        username: users
        password: users-password
        url: r2dbc:postgresql://localhost:5440/users-db
    datasource:
        driver-class-name: org.postgresql.Driver

front-url: https://front-keycloak.com
realmsPath: realms/user-management

keycloak:
    client-id: user-app-id
    client-secret: do50SQeKjXmfdh19pInaAywMiAT7xRvd
    server-url: ${front-url}
    realm: user-management
    mode: LOCAL

management:
    server:
        port: 8081
    metrics:
        distribution:
            slo:
                http.server.requests: 100ms, 200ms, 300ms, 400ms, 500ms
            percentiles-histogram:
                "[http.server.requests]": true
    endpoints:
        web.exposure.include: health, prometheus
        web:
            path-mapping:
                prometheus: "metrics"

# open api setup
springdoc:
    api-docs:
        enabled: true
        path: /swagger-docs/v3/api-docs
    swagger-ui.path: ${springdoc.api-docs.path}/swagger-ui.html

logging:
    stack-trace:
        print: true
        lines-max: 300
    level:
        root: info