spring:
    application:
        name: users-backend
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${front-url}/${realm}

server:
    port: ${APPLICATION_PORT}

front-url: ${KC_SERVICE_URL}
realm: realms/${REALM}

keycloak:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    server-url: ${front-url}
    realm: ${REALM}
    sslPath: ${SSL_PATH}

management:
    server:
        port: ${ACTUATOR_PORT}
    endpoints:
        web.exposure.include: health, prometheus
        web:
            path-mapping:
              prometheus: "metrics"

logging:
    stack-trace:
        print: true
        lines-max: 300
    level:
        org:
            springframework:
                security:
                    web:
                        server: ${LOG_SECURITY_LEVEL}