spring:
    application:
        name: users-backend
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: ${front-url}/${realmsPath}/protocol/openid-connect/certs

server:
    port: ${APPLICATION_PORT}

front-url: ${KC_SERVICE_URL}
realmsPath: realms/${REALM}

keycloak:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    server-url: ${front-url}
    realm: ${REALM}
    sslPath: ${SSL_PATH}

management:
    server:
        port: ${ACTUATOR_PORT}
    metrics:
        distribution:
            slo:
                http.server.requests: 100ms, 200ms, 300ms, 400ms, 500ms
            percentiles-histogram:
              "[http.server.requests]": true
    endpoints:
        web.exposure.include: health, prometheus
        web:
            path-mapping:
                prometheus: "metrics"

logging:
    stack-trace:
        print: true
        lines-max: 300
    level:
        org:
            springframework:
                security:
                    web:
                        server: ${LOG_SECURITY_LEVEL}