application:
    profile: cuber
    name: users-backend
    namespace: keycloak-ns
    containerPort: 8080
    containerPortName: app-port
    metricsPort: &metricsPort 8081
    serviceType: ClusterIP
    servicePort: 8080
    replicaCount: 1
    imagePrefix: "docker-image"
    version: 1.0.0
    pullPolicy: IfNotPresent
    logSecurityLevel: debug
    sslPath: "./cert/"
    javaOpts: "-XX:MaxRAMPercentage=75.0"

keycloak:
    secretName: keycloak-cert-ca-secret
    realm: realm
    clientId: clientId
    clientSecret: client-secret

livenessProbe:
    httpGet:
        scheme: HTTP
        path: /actuator/health
        port: *metricsPort
    initialDelaySeconds: 60

readinessProbe:
    httpGet:
        scheme: HTTP
        path: /actuator/health
        port: *metricsPort
    initialDelaySeconds: 60

resources:
    limits:
        cpu: 300m
        memory: 1Gi
    requests:
        cpu: 100m
        memory: 256Mi

monitoring:
    enabled: false
    metricsPath:

