global:
    applicationNs: application-ns
    usersDbConfigMap: users-db-config-map
    usersDbSecret: users-db-secret
    migrationEnabled: false

application:
    profile: cuber
    name: users-backend
    containerPort: 8080
    containerPortName: app-port
    metricsPort: &metricsPort 8081
    serviceType: ClusterIP
    servicePort: 8080
    replicaCount: 1
    imagePrefix: "docker-image"
    version: 1.0.0
    pullPolicy: IfNotPresent
    logSecurityLevel: info
    sslPath: "./cert/"
    javaOpts: "-XX:MaxRAMPercentage=75.0"

email:
    host: "https://any-server.com"
    port: 555
    username: "username"
    password: "password"
    emailSendTo: "test@email.com"

keycloak:
    serviceName: keycloak-service
    namespace: keycloak-ns
    secretName: keycloak-cert-ca-secret
    realm: realm
    clientId: clientId
    clientSecret: client-secret

livenessProbe:
    failureThreshold: 10
    httpGet:
        scheme: HTTP
        path: /actuator/health
        port: *metricsPort
    initialDelaySeconds: 60

readinessProbe:
    failureThreshold: 10
    httpGet:
        scheme: HTTP
        path: /actuator/health
        port: *metricsPort
    initialDelaySeconds: 60

resources:
    limits:
        cpu: 300m
        memory: 1Gi
    requests:
        cpu: 100m
        memory: 256Mi

monitoring:
    portName: actuator
    enabled: true
    monitoringLabelName: prometheus-monitored
    monitoringLabelValue: "prometheus"
    metricsPath: "/actuator/metrics"

