/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package users.backend.app

import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test

class AppTest {

    @Test fun testGetMessage() {
        if (false) {

        }
        assert(true)
    }
}
