{{- if not (lookup "v1" "Namespace" "" "keycloak-ns") }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.application.namespace }}
    annotations:
        "helm.sh/resource-policy": keep
{{- end -}}
