apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.application.name}}-config-map
    namespace: {{ .Values.application.namespace }}
    labels:
    {{- include "common.labels" . | indent 8 }}
data:
    KC_SERVICE_URL: https://{{ .Values.keycloak.serviceName }}.{{ .Values.keycloak.namespace }}.svc.cluster.local:443
    SPRING_PROFILE: {{ default "default" ( .Values.application.profile) | quote }}
    APPLICATION_PORT: {{ default 8080 ( .Values.application.containerPort ) | quote }}
    ACTUATOR_PORT: {{ default 8081 ( .Values.application.metricsPort ) | quote }}
    LOG_SECURITY_LEVEL: {{ .Values.application.logSecurityLevel | quote }}
    JAVA_OPTS: {{ .Values.application.javaOpts | quote }}