apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.application.name }}-secret
    namespace: {{ .Values.global.applicationNs }}
data:
    REALM: {{ .Values.keycloak.realm | b64enc }}
    CLIENT_ID: {{ .Values.keycloak.clientId | b64enc }}
    CLIENT_SECRET: {{ .Values.keycloak.clientSecret | b64enc }}
    SSL_PATH: {{ .Values.application.sslPath | b64enc }}
type: Opaque