apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.application.name }}-secret
    namespace: {{ .Values.global.applicationNs }}
data:
    REALM: {{ .Values.keycloak.realm | b64enc }}
    CLIENT_ID: {{ .Values.keycloak.clientId | b64enc }}
    CLIENT_SECRET: {{ .Values.keycloak.clientSecret | b64enc }}
    SSL_PATH: {{ .Values.application.sslPath | b64enc }}
    EMAIL_HOST: {{ .Values.email.host | b64enc }}
    EMAIL: {{ .Values.email.username | b64enc }}
    EMAIL_PASS: {{ .Values.email.password | b64enc }}
    EMAIL_SEND_TO: {{ .Values.email.emailSendTo | b64enc }}
type: Opaque