{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ .Values.application.name}}-monitor
    namespace: {{ .Values.application.namespace }}
    labels:
        app-monitoring: prometheus
spec:
    endpoints:
        - interval: 20s
          targetPort: {{ .Values.application.metricsPort }}
          path: {{ default "/actuator/prometheus" ( .Values.monitoring.metricsPath) | quote }}
    namespaceSelector:
        matchNames:
            - {{ .Values.application.namespace }}
    selector:
        matchLabels:
          {{ .Values.monitoring.monitoringLabelName }}: {{ .Values.monitoring.monitoringLabelValue }}
{{- end -}}
