apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.application.name }}-service
    namespace: {{ .Values.application.namespace }}
    labels:
    {{- include "common.labels" . | indent 8 }}
    {{- include "monitoring.labels" . | indent 8 }}
spec:
    type: {{ .Values.application.serviceType }}
    ports:
        - port: {{ .Values.application.servicePort }}
          name: http
          targetPort: {{ .Values.application.containerPortName }}
          protocol: TCP
        - port: {{ .Values.application.metricsPort }}
          name: {{ .Values.monitoring.portName }}
          targetPort: {{ .Values.monitoring.portName }}
          protocol: TCP
    selector:
    {{- include "common.labels" . | indent 8 -}}